// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
  console.warn("Missing Supabase environment variables. Database features may not work.");
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  },
  realtime: {
    params: {
      eventsPerSecond: 10,
    },
    // Exponential backoff for WebSocket reconnection
    reconnectAfterMs: (retries) => {
      console.log(`[realtime] Reconnecting attempt ${retries}...`);
      return Math.min(Math.pow(2, retries) * 1000, 30000);
    },
  }
});

// Device-scoped public settings must not inherit a stale/expired auth session.
// This client always sends the publishable anon key, allowing anonymous PWA
// users to sync prayer-notification preferences without a spurious 401.
export const supabasePublic = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    // Use a distinct key even though this client does not persist sessions.
    // Supabase warns when two GoTrue clients share the default auth storage key.
    storageKey: "noor-public-auth",
    persistSession: false,
    autoRefreshToken: false,
    detectSessionInUrl: false,
  },
});